### ISSUE TITLE
Add new lines before classes

### ISSUE THREAD

**Issue by jurgenzz** [Notinkham/sass-formatter#1]
example input:
```css
.class {
  display: block;
  .children {
      display: inline-block;
   }
}
```

desired output:

```css
.class {
  display: block;
  .children {
      display: inline-block;
   }
}
```
