### ISSUE TITLE
Bug in live version

### ISSUE THREAD

**Issue by jurgenzz** [Notinkham/sass-formatter#2]
Please fix web ui.

While testing it, code samples like: 

```css
.test { 
    color: '#ffffff'; 
    display: block; 
}
```

returns: 

```css
.test { 
}
```

and testing with nested scss
```scss
.test { 
    .test2 { 
        display: block; 
        color: '#ffffff'; 
    }
    color: '#ffffff'; 
    display: block; 
}
```

results in:
```scss
.test { 
    .test2 { 
        display: block; 
        color: '#ffffff'; 
    }
    color: '#ffffff'; 
    display: block; 
}
```
Where `.test` properties are not sorted correctly .
